services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: clothes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./distr/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clothes"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clothes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      db:
        condition: service_healthy
